name: C Project CI

on:
  push:
    branches:
      - '*'  # Run on all branches
  pull_request:
    branches:
      - '*'  # Run on all branches

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc libcurl4-openssl-dev libmicrohttpd-dev

      - name: Build and run tests
        env:
          PORT: 4006
        run: |
          gcc -o test_integration tests/test_integration.c -lcurl -Iinclude
          ./test_integration
          gcc -o server src/http_server.c src/palindrome.c src/main.c -lmicrohttpd -Iinclude

  docker-build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        env:
          PORT: 4006
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/palindrome-detection:latest .
          docker run -p 4006:4006 -e PORT=4006 ${{ secrets.DOCKER_USERNAME }}/palindrome-detection:latest