services:
  charcount:
    build:
      context: ./editor-charcount
    container_name: charcount-service
    ports:
      - "${CHARCOUNT_PORT}:${CHARCOUNT_PORT}"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${CHARCOUNT_PORT}"]
      interval: 10s
      timeout: 5s
      retries: 3
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${CHARCOUNT_PORT}
    networks:
      - editor-network

  wordcount:
    build:
      context: ./editor-wordcount
    container_name: wordcount-service
    ports:
      - "${WORDCOUNT_PORT}:${WORDCOUNT_PORT}"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${WORDCOUNT_PORT}"]
      interval: 10s
      timeout: 5s
      retries: 3
    environment:
      - PORT=${WORDCOUNT_PORT}
    networks:
      - editor-network

  frontend:
    build:
      context: ./editor-frontend
    container_name: frontend-service
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    depends_on:
      - charcount
      - wordcount
    environment:
      - CHARCOUNT_URL=http://charcount-service:${CHARCOUNT_PORT}
      - WORDCOUNT_URL=http://wordcount-service:${WORDCOUNT_PORT}
      - NODE_ENV=${NODE_ENV}
    networks:
      - editor-network

networks:
  editor-network:
    driver: bridge