version: "3.9"
services:
  charcount:
    build:
      context: ./editor-charcount
    container_name: charcount-service
    ports:
      - "4001:4001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4001"]
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      - NODE_ENV=production

  wordcount:
    build:
      context: ./editor-wordcount
    container_name: wordcount-service
    ports:
      - "4002:4002"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4002"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./editor-frontend
    container_name: frontend-service
    ports:
      - "3000:3000"
    depends_on:
      - charcount
      - wordcount
    environment:
      - CHARCOUNT_URL=http://charcount-service:4001
      - WORDCOUNT_URL=http://wordcount-service:4002
