services:
  reverse-proxy:
    build:
      context: ./editor-reverse-proxy
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./editor-frontend/src:/app/frontend/src
    depends_on:
      - charcount
      - wordcount
      - vowelcount
      - punctuationcount
      - avgwordlength
      - palindromedetection
    healthcheck:
      test: curl -f http://localhost:8080/health || exit 1
      interval: 10s
      timeout: 5s
      retries: 3

  frontend:
    build:
      context: ./editor-frontend
      dockerfile: Dockerfile
    environment:
      NODE_ENV: ${NODE_ENV}
    command: ["npm", "run", "build"]  # Build the static files during startup

  charcount:
    build:
      context: ./editor-charcount
      dockerfile: Dockerfile
    ports:
      - "${CHARCOUNT_PORT}:${CHARCOUNT_PORT}"  # Maps the port defined in .env  
    expose:
      - "${CHARCOUNT_PORT}"
    environment:
      PORT: ${CHARCOUNT_PORT}

  wordcount:
    build:
      context: ./editor-wordcount
      dockerfile: Dockerfile
    ports:
      - "${WORDCOUNT_PORT}:80"  # Maps the port defined in .env
    expose:
      - "80:${WORDCOUNT_PORT}"
    environment:
      PORT: ${WORDCOUNT_PORT}

  vowelcount:
    build:
      context: ./editor-vowelcount
      dockerfile: Dockerfile
    ports:
      - "${VOWELCOUNT_PORT}:${VOWELCOUNT_PORT}"  # Maps the port defined in .env
    expose:
      - "${VOWELCOUNT_PORT}"
    environment:
      PORT: ${VOWELCOUNT_PORT}

  punctuationcount:
    build:
      context: ./editor-punctuationcount
      dockerfile: Dockerfile
    ports:
      - "${PUNCTUATIONCOUNT_PORT}:${PUNCTUATIONCOUNT_PORT}"  # Maps the port defined in .env
    expose:
      - "${PUNCTUATIONCOUNT_PORT}"
    environment:
      PORT: ${PUNCTUATIONCOUNT_PORT}

  avgwordlength:
    build:
      context: ./editor-avgwordlength
      dockerfile: Dockerfile
    ports:
      - "${AVGWORDLENGTH_PORT}:${AVGWORDLENGTH_PORT}"  # Maps the port defined in .env  
    expose:
      - "${AVGWORDLENGTH_PORT}"
    environment:
      PORT: ${AVGWORDLENGTH_PORT}

  palindromedetection:
    build:
      context: ./editor-palindromedetection
      dockerfile: Dockerfile
    ports:
      - "${PALINDROMEDETECTION_PORT}:${PALINDROMEDETECTION_PORT}"  # Maps the port defined in .env
    expose:
      - "${PALINDROMEDETECTION_PORT}"
    environment:
      PORT: ${PALINDROMEDETECTION_PORT}