name: PHP CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-test:
    name: Lint and Test
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up PHP
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'  # Adjust this to match your PHP version
          extensions: mbstring, dom  # Add any necessary extensions

      # Step 3: Cache Composer dependencies
      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: ~/.composer/cache
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      # Step 4: Install dependencies
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      # Step 5: Run linting (optional, if you use PHP_CodeSniffer or other tools)
      - name: Run PHP linting
        run: php -l src/

      # Step 6: Run tests
      - name: Run tests
        run: composer test  # This runs "php vendor/bin/phpunit tests/" from your composer.json script

  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: lint-test

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build and push Docker image
      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/wordcount-app:latest -t ${{ secrets.DOCKER_USERNAME }}/wordcount-app:${{ github.sha }} .
          docker push ${{ secrets.DOCKER_USERNAME }}/wordcount-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/wordcount-app:${{ github.sha }}