name: CI Pipeline - Editor PunctuationCount

on:
  push:            # Trigger on any branch push
    branches:
      - '*'        # Wildcard to match all branches
  pull_request:    # Trigger for all pull requests
    branches:
      - '*'        # Wildcard to match pull requests to any branch

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Cache Cargo Registry
      uses: actions/cache@v3
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-registry-

    - name: Cache Cargo Index
      uses: actions/cache@v3
      with:
        path: ~/.cargo/git
        key: ${{ runner.os }}-cargo-git-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-git-

    - name: Build Project
      run: cargo build --release

    - name: Run Tests
      run: cargo test --release

  docker:
    name: Build and Push Docker Image
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Build Docker Image
      run: |
        docker build -t editor-punctuationcount .

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker Image
      run: |
        docker tag editor-punctuationcount:latest ${{ secrets.DOCKER_REPO }}/editor-punctuationcount:latest
        docker push ${{ secrets.DOCKER_REPO }}/editor-punctuationcount:latest